const router = require('express').Router();
const controller = require('../controllers/circles.controller');
const {id,body} = require('../middleware/validate');
router.get('/:id/members',id,controller.getMembers);
router.get('/:id/cycles',id,controller.getCycles);
router.get('/',controller.list);
router.post('/',body('circles'),controller.create);
router.get('/:id',id,controller.get);
router.put('/:id',id,body('circles'),controller.update);
router.delete('/:id',id,controller.remove);
module.exports = router;
